//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Glimpse.Localization {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Glimpse.Localization.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Content.
        /// </summary>
        public static string LoginSettingsViewModel_AboutContentMsg {
            get {
                return ResourceManager.GetString("LoginSettingsViewModel.AboutContentMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the language for the app.
        /// </summary>
        public static string LoginSettingsViewModel_SelectLanguageMsg {
            get {
                return ResourceManager.GetString("LoginSettingsViewModel.SelectLanguageMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account yet?.
        /// </summary>
        public static string LoginViewModel_NoAccountMsg {
            get {
                return ResourceManager.GetString("LoginViewModel.NoAccountMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        public static string LoginViewModel_OrMsg {
            get {
                return ResourceManager.GetString("LoginViewModel.OrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string LoginViewModel_SignInButton {
            get {
                return ResourceManager.GetString("LoginViewModel.SignInButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take A Glimpse.
        /// </summary>
        public static string LoginViewModel_TakeAGlimpse {
            get {
                return ResourceManager.GetString("LoginViewModel.TakeAGlimpse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up as a Vendor.
        /// </summary>
        public static string LoginViewModel_VendorSignUpButton {
            get {
                return ResourceManager.GetString("LoginViewModel.VendorSignUpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome To Glimpse.
        /// </summary>
        public static string LoginViewModel_WelcomeMsg {
            get {
                return ResourceManager.GetString("LoginViewModel.WelcomeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About this deal.
        /// </summary>
        public static string PromoDetailsViewModel_AboutThisDeal {
            get {
                return ResourceManager.GetString("PromoDetailsViewModel.AboutThisDeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Bought.
        /// </summary>
        public static string PromoDetailsViewModel_Bought {
            get {
                return ResourceManager.GetString("PromoDetailsViewModel.Bought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Content.
        /// </summary>
        public static string SettingsViewModel_AboutContentMsg {
            get {
                return ResourceManager.GetString("SettingsViewModel.AboutContentMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the language for the app.
        /// </summary>
        public static string SettingsViewModel_SelectLanguageMsg {
            get {
                return ResourceManager.GetString("SettingsViewModel.SelectLanguageMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect email or password..
        /// </summary>
        public static string SignInViewModel_IncorrectInputMsg {
            get {
                return ResourceManager.GetString("SignInViewModel.IncorrectInputMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required field..
        /// </summary>
        public static string SignInViewModel_MissingField {
            get {
                return ResourceManager.GetString("SignInViewModel.MissingField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sing in.
        /// </summary>
        public static string SignInViewModel_SignInButton {
            get {
                return ResourceManager.GetString("SignInViewModel.SignInButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is already being used.
        /// </summary>
        public static string VendorSignUpViewModel_ErrorEmailExistsMsg {
            get {
                return ResourceManager.GetString("VendorSignUpViewModel.ErrorEmailExistsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not valid.
        /// </summary>
        public static string VendorSignUpViewModel_ErrorEmailIsNotValidMsg {
            get {
                return ResourceManager.GetString("VendorSignUpViewModel.ErrorEmailIsNotValidMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required field.
        /// </summary>
        public static string VendorSignUpViewModel_ErrorMissingFieldMsg {
            get {
                return ResourceManager.GetString("VendorSignUpViewModel.ErrorMissingFieldMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match.
        /// </summary>
        public static string VendorSignUpViewModel_ErrorPasswordMatchMsg {
            get {
                return ResourceManager.GetString("VendorSignUpViewModel.ErrorPasswordMatchMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a Location.
        /// </summary>
        public static string VendorSignUpViewModel_LocationButton {
            get {
                return ResourceManager.GetString("VendorSignUpViewModel.LocationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string VendorSignUpViewModel_SignUp {
            get {
                return ResourceManager.GetString("VendorSignUpViewModel.SignUp", resourceCulture);
            }
        }
    }
}
