//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Glimpse.Localization {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings_Fr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_Fr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Glimpse.Localization.Strings_Fr", typeof(Strings_Fr).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voir la carte.
        /// </summary>
        public static string LikedPromotionsViewModel_SeeMap {
            get {
                return ResourceManager.GetString("LikedPromotionsViewModel.SeeMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to À propos du contenu.
        /// </summary>
        public static string LoginSettingsViewModel_AboutContentMsg {
            get {
                return ResourceManager.GetString("LoginSettingsViewModel.AboutContentMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionnez la langue de l&apos;application.
        /// </summary>
        public static string LoginSettingsViewModel_SelectLanguageMsg {
            get {
                return ResourceManager.GetString("LoginSettingsViewModel.SelectLanguageMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pas de compte?.
        /// </summary>
        public static string LoginViewModel_NoAccountMsg {
            get {
                return ResourceManager.GetString("LoginViewModel.NoAccountMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ou.
        /// </summary>
        public static string LoginViewModel_OrMsg {
            get {
                return ResourceManager.GetString("LoginViewModel.OrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se Connecter.
        /// </summary>
        public static string LoginViewModel_SignInButton {
            get {
                return ResourceManager.GetString("LoginViewModel.SignInButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faites un Apeçu.
        /// </summary>
        public static string LoginViewModel_TakeAGlimpse {
            get {
                return ResourceManager.GetString("LoginViewModel.TakeAGlimpse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inscrivez-vous comme fournisseur.
        /// </summary>
        public static string LoginViewModel_VendorSignUpButton {
            get {
                return ResourceManager.GetString("LoginViewModel.VendorSignUpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenu a Glimpse.
        /// </summary>
        public static string LoginViewModel_WelcomeMsg {
            get {
                return ResourceManager.GetString("LoginViewModel.WelcomeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to À propos de cette offre.
        /// </summary>
        public static string PromoDetailsViewModel_AboutThisDeal {
            get {
                return ResourceManager.GetString("PromoDetailsViewModel.AboutThisDeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Acheté.
        /// </summary>
        public static string PromoDetailsViewModel_Bought {
            get {
                return ResourceManager.GetString("PromoDetailsViewModel.Bought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to À propos du contenu.
        /// </summary>
        public static string SettingsViewModel_AboutContentMsg {
            get {
                return ResourceManager.GetString("SettingsViewModel.AboutContentMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionnez la langue de l&apos;application.
        /// </summary>
        public static string SettingsViewModel_SelectLanguageMsg {
            get {
                return ResourceManager.GetString("SettingsViewModel.SelectLanguageMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe oublié?.
        /// </summary>
        public static string SignInViewModel_ForgotPasswordMsg {
            get {
                return ResourceManager.GetString("SignInViewModel.ForgotPasswordMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email ou mot de passe incorrect..
        /// </summary>
        public static string SignInViewModel_IncorrectInputMsg {
            get {
                return ResourceManager.GetString("SignInViewModel.IncorrectInputMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Champ obligatoire manquant..
        /// </summary>
        public static string SignInViewModel_MissingField {
            get {
                return ResourceManager.GetString("SignInViewModel.MissingField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se connecter.
        /// </summary>
        public static string SignInViewModel_SignInButton {
            get {
                return ResourceManager.GetString("SignInViewModel.SignInButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Est déjà utilisé.
        /// </summary>
        public static string VendorSignUpViewModel_ErrorEmailExistsMsg {
            get {
                return ResourceManager.GetString("VendorSignUpViewModel.ErrorEmailExistsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;email n&apos;est pas valide.
        /// </summary>
        public static string VendorSignUpViewModel_ErrorEmailIsNotValidMsg {
            get {
                return ResourceManager.GetString("VendorSignUpViewModel.ErrorEmailIsNotValidMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Champ obligatoire manquant.
        /// </summary>
        public static string VendorSignUpViewModel_ErrorMissingFieldMsg {
            get {
                return ResourceManager.GetString("VendorSignUpViewModel.ErrorMissingFieldMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les mots de passe ne correspondent pas.
        /// </summary>
        public static string VendorSignUpViewModel_ErrorPasswordMatchMsg {
            get {
                return ResourceManager.GetString("VendorSignUpViewModel.ErrorPasswordMatchMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choisissez un lieu.
        /// </summary>
        public static string VendorSignUpViewModel_LocationButton {
            get {
                return ResourceManager.GetString("VendorSignUpViewModel.LocationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S&apos;inscrire.
        /// </summary>
        public static string VendorSignUpViewModel_SignUp {
            get {
                return ResourceManager.GetString("VendorSignUpViewModel.SignUp", resourceCulture);
            }
        }
    }
}
